---
- name: copy velociraptor binaries
  ansible.windows.win_copy:
    src: ../files/velociraptor-v0.72.0-windows-amd64.exe
    dest: c:\install\velociraptor\velociraptor-v0.72.0-windows-amd64.exe

- name: copy velociraptor config
  ansible.windows.win_copy:
    src: ../files/client.config.yaml
    dest: c:\install\velociraptor\client.config.yaml

- name: Stop velociraptor service
  ansible.windows.win_shell: stop-service velociraptor

- name: Install velociraptor service
  ansible.windows.win_command: c:\install\velociraptor\velociraptor-v0.72.0-windows-amd64.exe --config c:\install\velociraptor\client.config.yaml service install

    